eight_points_guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        api_city:
            base_url: "http://localhost:8080/"
            options:
                headers:
                    Accept: "application/json"
            plugin: ~