# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url:    ~ # Example: /foo/error403
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
            ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE]
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_memory:
            memory: ~
        webservice:
                    id: webservice_user_provider
    encoders:
            AppBundle\Security\User\WebserviceUser: bcrypt
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            provider: webservice
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator
            http_basic: ~
            form_login:
                # submit the login form here
                check_path: /login_check
                login_path: /login

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USER }
